### ISSUE TITLE
InstantClick breaks our JavaScript

### ISSUE THREAD

**Issue by fdoxyz** [thepracticaldev/codeland-copy#17]
While trying out Lisa's [most recent PR](https://github.com/thepracticaldev/codeland-copy/pull/16) I noticed our JS doesn't work when [InstantClick](https://docs.dev.to/frontend/instant-click/) preloads the page. 

This means that from the website, links will present our page but the event listeners won't work leaving almost all our features broken.

I think this can be solved by adding all our event listeners on `DOMContentLoaded` or using `window.InstantClick.on('change', ...`. I'll give this a try soon to be sure.

**Comment by joshpuetz** [comment]
@fdoxyz Was this ever solved?

**Comment by fdoxyz** [comment]
Yes, solved with #55. Closing now
